package com.whyalwasymea.bigboom.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.whyalwaysmea.bigboom.bean.db.DBCast;
import com.whyalwaysmea.bigboom.bean.db.DBMovie;

import com.whyalwasymea.bigboom.dao.DBCastDao;
import com.whyalwasymea.bigboom.dao.DBMovieDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dBCastDaoConfig;
    private final DaoConfig dBMovieDaoConfig;

    private final DBCastDao dBCastDao;
    private final DBMovieDao dBMovieDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dBCastDaoConfig = daoConfigMap.get(DBCastDao.class).clone();
        dBCastDaoConfig.initIdentityScope(type);

        dBMovieDaoConfig = daoConfigMap.get(DBMovieDao.class).clone();
        dBMovieDaoConfig.initIdentityScope(type);

        dBCastDao = new DBCastDao(dBCastDaoConfig, this);
        dBMovieDao = new DBMovieDao(dBMovieDaoConfig, this);

        registerDao(DBCast.class, dBCastDao);
        registerDao(DBMovie.class, dBMovieDao);
    }
    
    public void clear() {
        dBCastDaoConfig.clearIdentityScope();
        dBMovieDaoConfig.clearIdentityScope();
    }

    public DBCastDao getDBCastDao() {
        return dBCastDao;
    }

    public DBMovieDao getDBMovieDao() {
        return dBMovieDao;
    }

}
